root: true
parser: "@typescript-eslint/parser"
plugins:
  - prettier
  - "@typescript-eslint"
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/typescript
  - plugin:import/errors
  - plugin:import/warnings
  - prettier
  - plugin:prettier/recommended
  - prettier/@typescript-eslint
env:
  browser: true
  es6: true
parserOptions:
  ecmaVersion: 2018
  sourceType: module
overrides:
  - files:
      - webpack.*.js
    extends:
      - webpack
      - prettier
      - plugin:prettier/recommended
      - prettier/@typescript-eslint
    rules:
      "@typescript-eslint/no-var-requires": 0
