root: true
parser: "@typescript-eslint/parser"
plugins:
  - prettier
  - "@typescript-eslint"
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - prettier
  - plugin:prettier/recommended
  - prettier/@typescript-eslint
env:
  browser: true
  es6: true
parserOptions:
  sourceType: module
overrides:
  - files:
      - "*.test.ts"
    env:
      jest: true
  - files:
      - "*.config.js"
    env:
      node: true
    rules:
      "@typescript-eslint/no-var-requires": 0
